In [9]:
import pandas as pd

pd.set_option('display.max_columns', None)
#pd.reset_option('display.max_rows')
pd.set_option('display.max_rows', 20)  # ao inv√©s de none pode por INT do limite
pd.set_option('display.max_colwidth', 15)

In [10]:
df = pd.read_csv('../data/df_jogos.csv')

In [11]:
df

,id,Event,Site,Date,White,Black,Result,BlackElo,ECO,WhiteElo,White Short Castle,White Long Castle,Black Short Castle,Black Long Castle,Opposite side castling,Evals,WhiteWon,BlackWon,Moves,WhiteFinalPiecesCount,BlackFinalPiecesCount,FinalPiecesCount,QueenTrade
0,0,New York,New York,1918,"Morrison, J...","Marshall, F...",0-1,NaN,C89,NaN,1,0,1,0,0,"[38, 54, 25...",0,1,85,1,3,4,0
1,1168,New York,New York,1918,"Capablanca,...","Marshall, F...",1-0,NaN,C89,NaN,1,0,1,0,0,"[35, 43, 27...",1,0,36,7,5,12,0
2,1772,Brno,Brno,1921,"Sery, S.","Vecsey, Zoltan",1-0,NaN,C89,NaN,1,0,1,0,0,"[30, 54, 55...",1,0,17,12,10,22,0
3,2129,NLD-ch,Nijmegen,1921,"Te Kolste, ...","Loman, Rudolf",0-1,NaN,C89,NaN,1,0,1,0,0,"[37, 48, 46...",0,1,19,11,10,21,0
4,2522,USA sim,USA,1926,"Lasker, Ema...","Bigelow, Ho...",0-1,NaN,C89,NaN,1,0,1,0,0,"[26, 50, 52...",0,1,20,11,11,22,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,2113381,23rd Europe...,Terme Catez,2021,"Agopov,M","Ragger,M",1/2-1/2,2668.0,C89,2430.0,1,0,1,0,0,"[26, 28, 27...",0,0,55,2,1,3,1
2980,2117758,8th Sunway ...,Sitges,2021,"Kurmann,O","Van Dael,Siem",1-0,2300.0,C89,2466.0,1,0,1,0,0,"[25, 50, 41...",1,0,51,8,5,13,0
2981,2118961,7th Gashimo...,Baku,2021,"Karjakin,Se...","Caruana,F",1/2-1/2,2792.0,C89,2743.0,1,0,1,0,0,"[24, 37, 35...",0,0,37,4,4,8,1
2982,2119588,World Rapid...,Warsaw,2021,"Loskutova,V...","Abdumalik,Z",1-0,2491.0,C89,2100.0,1,0,1,0,0,"[34, 54, 45...",1,0,42,6,5,11,1
2983,2120268,World Rapid...,Warsaw,2021,"Dvirnyy,D","Lopusiewicz,P",1/2-1/2,2301.0,C89,2492.0,1,0,1,0,0,"[35, 50, 25...",0,0,88,0,0,0,1

In [12]:
evals_list = df['Evals'][0]
evals_list = evals_list.strip('[] ').split(",")
print(len(evals_list))
print(evals_list[-1])
print('=============')
print(min(evals_list))
print(max(evals_list))
print(type(evals_list))
evals_list

168
 -6153
=============
 -10
38
<class 'list'>

['38',
 ' 54',
 ' 25',
 ' 45',
 ' 37',
 ' 61',
 ' 50',
 ' 51',
 ' 35',
 ' 53',
 ' 43',
 ' 62',
 ' 69',
 ' 81',
 ' 56',
 ' 79',
 ' 50',
 ' 37',
 ' 12',
 ' -10',
 ' -4',
 ' 45',
 ' 39',
 ' 53',
 ' -43',
 ' -34',
 ' -59',
 ' -30',
 ' -97',
 ' -94',
 ' -184',
 ' -175',
 ' -152',
 ' -139',
 ' -331',
 ' -30',
 ' -18',
 ' -22',
 ' -22',
 ' -29',
 ' -30',
 ' 44',
 ' 47',
 ' 24',
 ' -44',
 ' -35',
 ' -53',
 ' -46',
 ' -58',
 ' -53',
 ' -84',
 ' -13',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' 0',
 ' -8',
 ' -23',
 ' -4',
 ' -70',
 ' -44',
 ' -75',
 ' -35',
 ' -112',
 ' -95',
 ' -238',
 ' -219',
 ' -271',
 ' -261',
 ' -274',
 ' -273',
 ' -233',
 ' -257',
 ' -238',
 ' -223',
 ' -273',
 ' -302',
 ' -256',
 ' -303',
 ' -278',
 ' -305',
 ' -333',
 ' 0',
 ' -328',
 ' -198',
 ' -205',
 ' -187',
 ' -192',
 ' -212',
 ' -226',
 ' -167',
 ' -214',
 ' -172',
 ' -215',
 ' -178',
 ' -193',
 ' -57',
 ' -186',
 ' -189',
 ' -182',
 ' -220',
 ' -197',
 ' -198',
 ' -238',
 ' -123',
 ' -174',
 ' -125',
 ' -113',
 ' -106',
 ' -106',
 ' -104',
 ' -74',
 ' -79',
 ' -203',
 ' -172',
 ' -207',
 ' -135',
 ' -273',
 ' -175',
 ' -160',
 ' -158',
 ' -215',
 ' -190',
 ' -185',
 ' -169',
 ' -189',
 ' -164',
 ' -196',
 ' -228',
 ' -329',
 ' -407',
 ' -405',
 ' -453',
 ' -503',
 ' -464',
 ' -528',
 ' -540',
 ' -549',
 ' -632',
 ' -604',
 ' -737',
 ' -791',
 ' -696',
 ' -813',
 ' -630',
 ' -631',
 ' -628',
 ' -671',
 ' -639',
 ' -661',
 ' -1060',
 ' -1114',
 ' -1175',
 ' -1324',
 ' -1311',
 ' -1699',
 ' -1758',
 ' -1910',
 ' -2174',
 ' -2249',
 ' -6153']

In [13]:

import ast
dados = []

for index, row in df.iterrows():
    linha = {}
    
    # initializing string representation of a list
    evals_list = row['Evals']

    # Converting string to list
    evals_list = ast.literal_eval(evals_list)

    linha['id'] = row['id']
    linha['MaxEval'] = max(evals_list)
    linha['MinEval'] = min(evals_list)
    linha['FinalEval'] = evals_list[-1]

    linha['W<=10'] = 0
    linha['W<=25'] = 0
    linha['W<=50'] = 0
    linha['W<=100'] = 0
    linha['W<=200'] = 0
    linha['W<=500'] = 0
    linha['W>500'] = 0
    linha['B<=10'] = 0
    linha['B<=25'] = 0
    linha['B<=50'] = 0
    linha['B<=100'] = 0
    linha['B<=200'] = 0
    linha['B<=500'] = 0
    linha['B>500'] = 0

    linha['Wprojection'] = 0
    linha['Bprojection'] = 0


    
    turn = False #true branca, false preta
    first = True #primeira jogada
    jogada_anterior = 0
    jogada_atual = 0
    direction = 0 #1 subindo, -1 descendo
    for eval in evals_list:
        turn = not turn
        jogada_atual = eval

        #testa se √© o primeiro lance
        if first:
            jogada_anterior = jogada_atual
            first = False
            continue

        #testa de quem √© a jogada
        if turn: #branca
            var = abs(jogada_anterior - jogada_atual)
            #testa dire√ß√£o da varia√ß√£o
            if jogada_anterior >= jogada_atual:
                if var <= 10:
                    linha['W<=10'] += 1
                elif var <= 25:
                    linha['W<=25'] += 1
                elif var <= 50:
                    linha['W<=50'] += 1
                elif var <= 100:
                    linha['W<=100'] += 1
                elif var <= 200:
                    linha['W<=200'] += 1
                elif var <= 500:
                    linha['W<=500'] += 1
                else:
                    linha['W>500'] += 1
            else:
                if var <= 10:
                    linha['W<=10'] += 1
                
        else: #preta
            var = abs(jogada_anterior - jogada_atual)
            #testa dire√ß√£o da varia√ß√£o
            if jogada_anterior >= jogada_atual:
                linha['B<=10'] += 1
            else:
                if var <= 10:
                    linha['B<=10'] += 1
                elif var <= 25:
                    linha['B<=25'] += 1
                elif var <= 50:
                    linha['B<=50'] += 1
                elif var <= 100:
                    linha['B<=100'] += 1
                elif var <= 200:
                    linha['B<=200'] += 1
                elif var <= 500:
                    linha['B<=500'] += 1
                else:
                    linha['B>500'] += 1

        #Proje√ß√£o das evaluation
        if jogada_atual > 0:
            if jogada_atual < 1000:
                linha['Wprojection'] += jogada_atual
            else:
                linha['Wprojection'] += 1000
        else:
            if jogada_atual > -1000:
                linha['Bprojection'] += jogada_atual
            else:
                linha['Bprojection'] += -1000
        
        jogada_anterior = jogada_atual

    linha['DifProjection'] = linha['Wprojection'] + linha['Bprojection']
    dados.append(linha)

df_evals = pd.DataFrame(dados)
df_evals.to_csv('../data/df_evals.csv', index=False)

In [14]:
df_evals

,id,MaxEval,MinEval,FinalEval,W<=10,W<=25,W<=50,W<=100,W<=200,W<=500,W>500,B<=10,B<=25,B<=50,B<=100,B<=200,B<=500,B>500,Wprojection,Bprojection,DifProjection
0,0,81,-6153,-6153,21,13,13,13,9,2,0,44,18,10,6,4,2,0,1152,-38380,-37228
1,1168,99995,27,99995,13,3,5,3,1,0,0,15,5,7,3,4,0,1,17855,0,17855
2,1772,99999,3,99999,9,2,2,0,0,0,0,9,5,0,1,0,0,1,3851,0,3851
3,2129,133,-972,-972,9,3,2,0,1,0,1,8,6,1,2,1,0,0,2030,-1888,142
4,2522,109,-1187,-1187,9,2,2,0,0,3,0,15,2,1,1,0,0,0,1406,-6327,-4921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,2113381,417,-49,-49,17,15,7,4,1,2,0,32,7,6,6,1,2,0,15091,-100,14991
2980,2117758,99999,0,99999,19,8,5,5,3,1,0,22,7,9,5,3,2,2,28811,0,28811
2981,2118961,102,-8,0,16,12,2,0,1,0,0,25,6,3,2,0,0,0,2788,-9,2779
2982,2119588,778,-8,778,19,8,4,2,0,0,0,20,8,5,6,1,1,0,25803,-8,25795
2983,2120268,91,-774,0,52,9,7,4,4,2,1,63,10,3,7,1,2,1,1658,-34133,-32475