In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
#pd.reset_option('display.max_rows')
pd.set_option('display.max_rows', 20)  # ao invés de none pode por INT do limite
pd.set_option('display.max_colwidth', 15)

In [2]:
df_soevals = pd.read_csv('../data/df_jogos.csv')[['id','Evals']] #aqui há dados errados (roque) porém tem a computação das evals, que demora 5 horas (a qual está correta)
df_evals = pd.read_csv('../data/df_evals.csv') #analise das evals
df_jogos = pd.read_csv('../data/df_jogos_semeval.csv') #os dados dos jogos corretos mas sem as evals
df_plays = pd.read_csv('../data/df_plays.csv')  #os dados das linhas jogadas

In [3]:
df_jogos.drop(columns=['White Short Castle', 'White Long Castle','Black Short Castle', 'Black Long Castle', 'Opposite side castling'], inplace=True)

In [4]:
df = df_jogos.merge(df_soevals, on='id').merge(df_evals, on='id').merge(df_plays, on='id')
df.to_csv('../data/df_completo.csv', index=False)

In [5]:
df

,id,Event,Site,Date,White,Black,Result,BlackElo,ECO,WhiteElo,WhiteWon,BlackWon,Moves,WhiteFinalPiecesCount,BlackFinalPiecesCount,FinalPiecesCount,QueenTrade,Evals,MaxEval,MinEval,FinalEval,W<=10,W<=25,W<=50,W<=100,W<=200,W<=500,W>500,B<=10,B<=25,B<=50,B<=100,B<=200,B<=500,B>500,Wprojection,Bprojection,DifProjection,Plays
0,0,New York,New York,1918,"Morrison, J...","Marshall, F...",0-1,NaN,C89,NaN,0,1,85,1,3,4,0,"[38, 54, 25...",81,-6153,-6153,21,13,13,13,9,2,0,44,18,10,6,4,2,0,1152,-38380,-37228,1. e4 e5 2....
1,1168,New York,New York,1918,"Capablanca,...","Marshall, F...",1-0,NaN,C89,NaN,1,0,36,7,5,12,0,"[35, 43, 27...",99995,27,99995,13,3,5,3,1,0,0,15,5,7,3,4,0,1,17855,0,17855,1. e4 e5 2....
2,1772,Brno,Brno,1921,"Sery, S.","Vecsey, Zoltan",1-0,NaN,C89,NaN,1,0,17,12,10,22,0,"[30, 54, 55...",99999,3,99999,9,2,2,0,0,0,0,9,5,0,1,0,0,1,3851,0,3851,1. e4 e5 2....
3,2129,NLD-ch,Nijmegen,1921,"Te Kolste, ...","Loman, Rudolf",0-1,NaN,C89,NaN,0,1,19,11,10,21,0,"[37, 48, 46...",133,-972,-972,9,3,2,0,1,0,1,8,6,1,2,1,0,0,2030,-1888,142,1. e4 e5 2....
4,2522,USA sim,USA,1926,"Lasker, Ema...","Bigelow, Ho...",0-1,NaN,C89,NaN,0,1,20,11,11,22,0,"[26, 50, 52...",109,-1187,-1187,9,2,2,0,0,3,0,15,2,1,1,0,0,0,1406,-6327,-4921,1. e4 e5 2....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,2113381,23rd Europe...,Terme Catez,2021,"Agopov,M","Ragger,M",1/2-1/2,2668.0,C89,2430.0,0,0,55,2,1,3,1,"[26, 28, 27...",417,-49,-49,17,15,7,4,1,2,0,32,7,6,6,1,2,0,15091,-100,14991,1. e4 e5 2....
2980,2117758,8th Sunway ...,Sitges,2021,"Kurmann,O","Van Dael,Siem",1-0,2300.0,C89,2466.0,1,0,51,8,5,13,0,"[25, 50, 41...",99999,0,99999,19,8,5,5,3,1,0,22,7,9,5,3,2,2,28811,0,28811,1. e4 e5 2....
2981,2118961,7th Gashimo...,Baku,2021,"Karjakin,Se...","Caruana,F",1/2-1/2,2792.0,C89,2743.0,0,0,37,4,4,8,1,"[24, 37, 35...",102,-8,0,16,12,2,0,1,0,0,25,6,3,2,0,0,0,2788,-9,2779,1. e4 e5 2....
2982,2119588,World Rapid...,Warsaw,2021,"Loskutova,V...","Abdumalik,Z",1-0,2491.0,C89,2100.0,1,0,42,6,5,11,1,"[34, 54, 45...",778,-8,778,19,8,4,2,0,0,0,20,8,5,6,1,1,0,25803,-8,25795,1. e4 e5 2....
2983,2120268,World Rapid...,Warsaw,2021,"Dvirnyy,D","Lopusiewicz,P",1/2-1/2,2301.0,C89,2492.0,0,0,88,0,0,0,1,"[35, 50, 25...",91,-774,0,52,9,7,4,4,2,1,63,10,3,7,1,2,1,1658,-34133,-32475,1. e4 e5 2....