In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
#pd.reset_option('display.max_rows')
pd.set_option('display.max_rows', 20)  # ao inv√©s de none pode por INT do limite
pd.set_option('display.max_colwidth', 15)

In [2]:
df = pd.read_csv('../data/df_subvar_9-10.csv')

In [3]:
df_players = pd.read_csv('../data/players_list_fide.csv', sep=';')
df_players.head()

             Name  Fed
0  A Abdel Maa...  EGY
1          A Aman  IND
2  A B M Hasib...  BAN
3  A B M Jobai...  BAN
4  A B M Musta...  BAN

In [4]:
russ_list = [
'Armenia',
'Azerbaijan',
'Belarus',
'Estonia',
'Georgia',
'Kazakhstan',
'Kyrgyzstan',
'Latvia',
'Lithuania',
'Moldova',
'Russia',
'Tajikistan',
'Turkmenistan',
'Ukraine',
'Uzbekistan']

In [5]:
df_fide = pd.read_csv('../data/fide_feds.csv', sep=';')
df_fide.head()

          country  fed continent
0          Russia  RUS    Europe
1  United Stat...  USA  Americas
2           China  CHN      Asia
3           India  IND      Asia
4         Ukraine  UKR    Europe

In [6]:
count = -1
for index, row in df.iterrows():
    count += 1
    print('{0}\t\t'.format(count), end='\r')
    white = row['White']
    black = row['Black']

    wname = df_players.loc[df_players['Name'] == white]['Fed'].tolist()
    bname = df_players.loc[df_players['Name'] == black]['Fed'].tolist()

    if len(wname) == 0:
        wname = np.NaN
        wfed = np.NaN
    else:
        wname = wname[0]
        wfed = df_fide.loc[df_fide['fed'] == wname]['continent'].tolist()[0]
        wcountry = df_fide.loc[df_fide['fed'] == wname]['country'].tolist()[0]

        if wcountry in russ_list:
            wfed = 'URSS'


    if len(bname) == 0:
        bname = np.NaN
        bfed = np.NaN
    else:
        bname = bname[0]
        bfed = df_fide.loc[df_fide['fed'] == bname]['continent'].tolist()[0]
        bcountry = df_fide.loc[df_fide['fed'] == bname]['country'].tolist()[0]

        if bcountry in russ_list:
            wfed = 'URSS'

    df.loc[index, 'WhiteRegion'] = wfed
    df.loc[index, 'BlackRegion'] = bfed

In [7]:
copia = df.copy()

In [8]:
df = copia.copy()

In [9]:
#df = df.loc[(df['WhiteElo'] >= 2000) | (df['WhiteElo'].isna())]
#df = df.loc[(df['BlackElo'] >= 2000) | (df['BlackElo'].isna())]

In [10]:
df['WGoodMoves'] = df['W<=10'] + df['W<=25'] + df['W<=50']
df['BGoodMoves'] = df['B<=10'] + df['B<=25'] + df['B<=50']
df['WBadMoves'] = df['W<=100'] + df['W<=200'] + df['W<=500'] + df['W>500']
df['BBadMoves'] = df['B<=100'] + df['B<=200'] + df['B<=500'] + df['B>500']
df.columns

Index(['id', 'Event', 'Site', 'Date', 'White', 'Black', 'Result', 'BlackElo',
       'ECO', 'WhiteElo', 'WhiteWon', 'BlackWon', 'Moves',
       'WhiteFinalPiecesCount', 'BlackFinalPiecesCount', 'FinalPiecesCount',
       'QueenTrade', 'Evals', 'MaxEval', 'MinEval', 'FinalEval', 'W<=10',
       'W<=25', 'W<=50', 'W<=100', 'W<=200', 'W<=500', 'W>500', 'B<=10',
       'B<=25', 'B<=50', 'B<=100', 'B<=200', 'B<=500', 'B>500', 'Wprojection',
       'Bprojection', 'DifProjection', 'Plays', 'SubVariation', 'Mainline',
       'WhiteRegion', 'BlackRegion', 'WGoodMoves', 'BGoodMoves', 'WBadMoves',
       'BBadMoves'],
      dtype='object')

In [11]:
df = df[['Date', 'BlackElo', 'WhiteElo', 'SubVariation', 'WGoodMoves','BGoodMoves', 'WBadMoves', 'BBadMoves', 'WhiteRegion', 'BlackRegion']]

In [12]:
df

,Date,BlackElo,WhiteElo,SubVariation,WGoodMoves,BGoodMoves,WBadMoves,BBadMoves,WhiteRegion,BlackRegion
0,1918,NaN,NaN,9. exd5 Nxd...,47,72,24,12,NaN,NaN
1,1918,NaN,NaN,9. exd5 Nxd...,21,27,4,8,NaN,NaN
2,1921,NaN,NaN,9. exd5 Nxd...,13,14,0,2,NaN,NaN
3,1921,NaN,NaN,9. exd5 Nxd...,14,15,2,3,NaN,NaN
4,1926,NaN,NaN,9. exd5 Nxd...,13,18,3,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2979,2021,2668.0,2430.0,9. exd5 Nxd...,39,45,7,9,NaN,NaN
2980,2021,2300.0,2466.0,9. exd5 Nxd...,32,38,9,12,NaN,NaN
2981,2021,2792.0,2743.0,9. exd5 Nxd...,30,34,1,2,NaN,NaN
2982,2021,2491.0,2100.0,9. exd5 Nxd...,31,33,2,8,NaN,NaN
2983,2021,2301.0,2492.0,9. exd5 Nxd...,68,76,11,11,NaN,NaN

In [13]:
# Separar nas sete varia√ß√µes mais comuns e nas demais
common_variations = ['9. d3 dxe4 10. dxe4 Qxd1',
'9. d4 Nxe4 10. dxe5 Be6',
'9. d4 exd4 10. e5 Ne4',
'9. exd5 Nxd5 10. Nxe5 Nxe5',
'9. exd5 Nxd5 10. d4 exd4',
'9. exd5 e4 10. Ng5 Bg4',
'9. exd5 e4 10. dxc6 exf3']

for index, row in df.iterrows():
    if row['SubVariation'] not in common_variations:
        df.loc[index, 'SubVariation'] = 'Other'

In [14]:
df

,Date,BlackElo,WhiteElo,SubVariation,WGoodMoves,BGoodMoves,WBadMoves,BBadMoves,WhiteRegion,BlackRegion
0,1918,NaN,NaN,9. exd5 Nxd...,47,72,24,12,NaN,NaN
1,1918,NaN,NaN,9. exd5 Nxd...,21,27,4,8,NaN,NaN
2,1921,NaN,NaN,9. exd5 Nxd...,13,14,0,2,NaN,NaN
3,1921,NaN,NaN,9. exd5 Nxd...,14,15,2,3,NaN,NaN
4,1926,NaN,NaN,9. exd5 Nxd...,13,18,3,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2979,2021,2668.0,2430.0,9. exd5 Nxd...,39,45,7,9,NaN,NaN
2980,2021,2300.0,2466.0,9. exd5 Nxd...,32,38,9,12,NaN,NaN
2981,2021,2792.0,2743.0,9. exd5 Nxd...,30,34,1,2,NaN,NaN
2982,2021,2491.0,2100.0,9. exd5 Nxd...,31,33,2,8,NaN,NaN
2983,2021,2301.0,2492.0,9. exd5 Nxd...,68,76,11,11,NaN,NaN

In [15]:
variations = df['SubVariation'].unique().tolist()
print(len(variations))
variations

8

['9. exd5 Nxd5 10. d4 exd4',
 '9. exd5 Nxd5 10. Nxe5 Nxe5',
 'Other',
 '9. exd5 e4 10. dxc6 exf3',
 '9. d3 dxe4 10. dxe4 Qxd1',
 '9. d4 Nxe4 10. dxe5 Be6',
 '9. d4 exd4 10. e5 Ne4',
 '9. exd5 e4 10. Ng5 Bg4']

In [16]:
#sdf = pd.get_dummies(df)

In [17]:
df

,Date,BlackElo,WhiteElo,SubVariation,WGoodMoves,BGoodMoves,WBadMoves,BBadMoves,WhiteRegion,BlackRegion
0,1918,NaN,NaN,9. exd5 Nxd...,47,72,24,12,NaN,NaN
1,1918,NaN,NaN,9. exd5 Nxd...,21,27,4,8,NaN,NaN
2,1921,NaN,NaN,9. exd5 Nxd...,13,14,0,2,NaN,NaN
3,1921,NaN,NaN,9. exd5 Nxd...,14,15,2,3,NaN,NaN
4,1926,NaN,NaN,9. exd5 Nxd...,13,18,3,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2979,2021,2668.0,2430.0,9. exd5 Nxd...,39,45,7,9,NaN,NaN
2980,2021,2300.0,2466.0,9. exd5 Nxd...,32,38,9,12,NaN,NaN
2981,2021,2792.0,2743.0,9. exd5 Nxd...,30,34,1,2,NaN,NaN
2982,2021,2491.0,2100.0,9. exd5 Nxd...,31,33,2,8,NaN,NaN
2983,2021,2301.0,2492.0,9. exd5 Nxd...,68,76,11,11,NaN,NaN

In [18]:
df.columns

Index(['Date', 'BlackElo', 'WhiteElo', 'SubVariation', 'WGoodMoves',
       'BGoodMoves', 'WBadMoves', 'BBadMoves', 'WhiteRegion', 'BlackRegion'],
      dtype='object')

# Regress√£o Linear

In [19]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np

from stargazer.stargazer import Stargazer #visualizar diferentes modelos

In [20]:
model = smf.ols(formula="Q('WGoodMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
       C(SubVariation) + C(WhiteRegion) + C(BlackRegion)", data=df)

res_Wgm = model.fit()
#res_Wgm.summary()

In [21]:
model = smf.ols(formula="Q('WBadMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
         C(SubVariation) + C(WhiteRegion) + C(BlackRegion)", data=df)

res_Wbm = model.fit()
#res_Wbm.summary()

In [22]:
model = smf.ols(formula="Q('BGoodMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
        C(SubVariation) + C(WhiteRegion) + C(BlackRegion)", data=df)

res_Bgm = model.fit()
#res_Bgm.summary()

In [23]:
model = smf.ols(formula="Q('BBadMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
        C(SubVariation) + C(WhiteRegion) + C(BlackRegion)", data=df)

res_Bbm = model.fit()
#res_Bbm.summary()

In [24]:
stargazer = Stargazer([res_Wgm, res_Wbm, res_Bgm, res_Bbm])
stargazer

# backup

In [25]:
model = smf.ols(formula="Q('WGoodMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
        C(SubVariation)", data=df)

res_Wgm = model.fit()
#res_Wgm.summary()

In [26]:
model = smf.ols(formula="Q('WBadMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
        C(SubVariation)", data=df)

res_Wbm = model.fit()
#res_Wbm.summary()

In [27]:
model = smf.ols(formula="Q('BGoodMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
        C(SubVariation)", data=df)

res_Bgm = model.fit()
#res_Bgm.summary()

In [28]:
model = smf.ols(formula="Q('BBadMoves') ~  Q('Date') + Q('BlackElo') + Q('WhiteElo') + \
        C(SubVariation)", data=df)

res_Bbm = model.fit()
#res_Bbm.summary()

In [29]:
stargazer = Stargazer([res_Wgm, res_Wbm, res_Bgm, res_Bbm])
stargazer